"""Semantic search over veterinary clinical cases in Qdrant.

The embedding is generated by the vision-service (SapBERT endpoint),
so this module does NOT need torch — only HTTP + Qdrant client.
"""

import logging

import httpx
from qdrant_client import QdrantClient
from qdrant_client.models import Filter, FieldCondition, MatchValue

from src.config import settings
from src.rag.qdrant_schema import COLLECTION_NAME, get_qdrant_client

logger = logging.getLogger(__name__)

EMBED_URL = f"{settings.vision_service_url.rstrip('/')}/vision/embed"


async def _get_embedding(text: str) -> list[float]:
    """Call vision-service /embed endpoint to get SapBERT vector."""
    async with httpx.AsyncClient(timeout=10.0) as client:
        resp = await client.get(EMBED_URL, params={"text": text})
        resp.raise_for_status()
        return resp.json()["vector"]


def _build_filter(source: str | None = None, record_type: str | None = None) -> Filter | None:
    conditions = []
    if source:
        conditions.append(FieldCondition(key="source", match=MatchValue(value=source)))
    if record_type:
        conditions.append(FieldCondition(key="record_type", match=MatchValue(value=record_type)))
    if not conditions:
        return None
    return Filter(must=conditions)


async def semantic_search(
    query: str,
    limit: int = 5,
    source: str | None = None,
    record_type: str | None = None,
) -> list[dict]:
    """Search clinical cases by semantic similarity.

    Returns list of {id, text, score, source, record_type}.
    """
    embedding = await _get_embedding(query)
    client = get_qdrant_client()

    results = client.search(
        collection_name=COLLECTION_NAME,
        query_vector=embedding,
        query_filter=_build_filter(source, record_type),
        limit=limit,
        with_payload=True,
    )

    return [
        {
            "id": hit.payload.get("point_id", str(hit.id)),
            "text": hit.payload.get("text", ""),
            "score": round(hit.score, 4),
            "source": hit.payload.get("source", ""),
            "record_type": hit.payload.get("record_type", ""),
        }
        for hit in results
    ]
